AllCops:
  Exclude:
      - 'vendor/**/*'
      - '.git/**/*'
      # Really not fussed too much about the quality of the migrations code
      - 'db/migrate/*'
      - 'db/schema.rb'
      - 'provisioning/**/*'
      - 'bin/*'

# We prefer double quotes here and it we're making liberal use of multi-line
# strings so it makes sense to enforce those to be consistent oo
Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

# This one I disagree with. Putting seperators in large numbers makes sense
# in some circumstances but in others (an example id in a database table)
# it's just nonsensical. Also, I think this one might also be a bit US centric.
Style/NumericLiterals:
  Enabled: false

# Everything below here we are disabling temporarily just so that we can
# get most of the code in a good state with respect to fairly trivial
# code changes

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false
