AllCops:
  Exclude:
      - 'vendor/**/*'
      - '.git/**/*'
      # Really not fussed too much about the quality of the migrations code
      - 'db/migrate/*'
      - 'db/schema.rb'

Style/StringLiterals:
  EnforcedStyle: double_quotes

# Everything below here we are disabling temporarily just so that we can
# get most of the code in a good state with respect to fairly trivial
# code changes

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
