version: '3'
services:
  web:
    build:
      context: .
      dockerfile: dockerfiles/web
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - db
      - redis
      - smtp

  db:
    image: postgres:10.5
    ports:
      - "5432"

  smtp:
    build:
      context: .
      dockerfile: dockerfiles/smtp
    volumes:
      - .:/app
    ports:
      - "2525:2525"

  redis:
    image: redis:4.0

  worker:
    build:
      context: .
      dockerfile: dockerfiles/worker
    volumes:
      - .:/app
    links:
      - redis

  postfix:
    build:
      context: .
      dockerfile: dockerfiles/postfix
    volumes:
      - .:/app
