version: '3'
services:
  web:
    build:
      context: .
      dockerfile: dockerfiles/web
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - db
      - redis
  db:
    image: postgres:10.5
    ports:
      - "5432"
  redis:
    image: redis:4.0
  postfix:
    build:
      context: .
      dockerfile: dockerfiles/postfix
    volumes:
      - .:/app
